#!/bin/sh
# (cf. https://blog.alexellis.io/get-started-with-openfaas-and-kind/)
echo install go...
apt-get install -y golang-go
echo get kind...
go get sigs.k8s.io/kind
ln -s $HOME/go/bin/kind $VAGRANT_USER_HOME/bin
echo create openfaas cluster...
$HOME/go/bin/kind create cluster --name openfaas
echo determine kubeconfig...
export KUBECONFIG=$($HOME/go/bin/kind get kubeconfig-path --name=openfaas)
echo KUBECONFIG: $KUBECONFIG